/**
 * Script to generate a JavaScript file containing all dataset markdown files
 * This allows the React app to upload the content to the backend for RAG functionality
 * 
 * Run with: node scripts/generateDataset.js
 */

const fs = require('fs');
const path = require('path');

const DATASET_DIR = path.join(__dirname, '..', 'dataset');
const OUTPUT_FILE = path.join(__dirname, '..', 'frontend', 'src', 'data', 'datasetContent.js');

// Ensure output directory exists
const outputDir = path.dirname(OUTPUT_FILE);
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Read all markdown files from dataset directory
const files = fs.readdirSync(DATASET_DIR)
  .filter(file => file.endsWith('.md') && file !== 'README.md')
  .sort(); // Ensure consistent ordering

console.log(`Found ${files.length} markdown files to process...`);

// Generate the dataset array
const datasetEntries = files.map(filename => {
  const filePath = path.join(DATASET_DIR, filename);
  const content = fs.readFileSync(filePath, 'utf8');
  
  // Extract title from first line (assuming it starts with #)
  const lines = content.split('\n');
  const titleLine = lines.find(line => line.trim().startsWith('#'));
  const title = titleLine ? titleLine.replace(/^#+\s*/, '').trim() : filename.replace('.md', '');
  
  // Extract ID from filename (e.g., "01" from "01_fundamentals_big_o.md")
  const id = filename.split('_')[0];
  
  console.log(`✓ Processed: ${filename} (${title})`);
  
  return {
    id,
    title,
    filename,
    content: content.replace(/`/g, '\\`').replace(/\$/g, '\\$') // Escape template literal special chars
  };
});

// Generate the JavaScript file
const jsContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/generateDataset.js
 * Contains all dataset markdown content for uploading to backend
 */

export const datasetContent = ${JSON.stringify(datasetEntries, null, 2)};

export const datasetInfo = {
  totalDocuments: ${datasetEntries.length},
  generatedAt: '${new Date().toISOString()}',
  documents: ${JSON.stringify(datasetEntries.map(d => ({ id: d.id, title: d.title, filename: d.filename })), null, 2)}
};
`;

// Write the file
fs.writeFileSync(OUTPUT_FILE, jsContent, 'utf8');

console.log(`\n✅ Successfully generated ${OUTPUT_FILE}`);
console.log(`   Total documents: ${datasetEntries.length}`);
console.log(`   Total size: ${(jsContent.length / 1024 / 1024).toFixed(2)} MB`);
console.log('\nYou can now run the React app and it will automatically upload this data to the backend!');

